### ISSUE TITLE
Command menu controller scrolling broken

### ISSUE THREAD

**Issue by Redund0** [Wet-Boys/LookingGlass#10]
Looks like with other mods command scrolling with controller doesn't not work well, directional buttons either not working or going to seemingly random items in the menu. Tried on another profile that was mostly vanilla and it worked fine.

Profile code with issue:
018f68b3-cbb9-5fca-3a0a-04705465cc3f

**Comment by ToastedOven** [comment]
Fixed in v1.2.2, thanks for the report!

**Comment by Redund0** [comment]
It seems like the issue was fixed for white rarity box, but not Green, Red, or the scrapper.

**Comment by ToastedOven** [comment]
Think I got the real fix out now, sorry about that
