### ISSUE TITLE
CommandQueue Menu not showing

### ISSUE THREAD

**Issue by yvsaint** [Wet-Boys/LookingGlass#100]
I've got all dependencies for CommandQueue and for LookingGlass but the UI just simply doesn't appear.

**Comment by ToastedOven** [comment]
Duplicate it #98 , please post any info you have (preferably a log/profile code) there. I've finally got some time so I can take a look at it tomorrow or the next day at worst

**Comment by yvsaint** [comment]
Just straight up wont work. BUT there was this once instance where when I loaded into a run and held tab and it was there, there was also like a dupe on the numbers for the items overlapping the original. I don't know how I did that either just happened. Might be related or not but yea that's all. Also how do I get a profile code or log?
![image](https://github.com/user-attachments/assets/4e56fd4a-2540-4dee-84b5-1be294553760)

**Comment by ToastedOven** [comment]
Again, please post info in #98 to consolidate information about the same problem.
![r2modman_qipANcFH6k](https://github.com/user-attachments/assets/f2ebc657-7ee6-49f1-b28a-55a60a4c654e)
![r2modman_DSPTt3KK98](https://github.com/user-attachments/assets/57902596-9b90-4d21-a446-eb3b8b461e50)

**Comment by yvsaint** [comment]
ah ok sorry ill do that now
