### ISSUE TITLE
Stats Only Updating When Pressing Tab

### ISSUE THREAD

**Issue by RagingCownipples** [Wet-Boys/LookingGlass#106]
the entire Stats ui is only updating when tab is pressed. wont update otherwise.

**Comment by ToastedOven** [comment]
I saw someone else had the similar issue but when I test I see it working normally, can you share a mod list so that I can see. It's probably a conflict

**Comment by RagingCownipples** [comment]
![image](https://github.com/user-attachments/assets/cde4c40e-658b-4324-b860-930bd3433eee)
these are the only mods i have installed.

**Comment by ToastedOven** [comment]
could you send a log file of a run with it not working? Maybe your end will show something then

**Comment by RagingCownipples** [comment]
Well that's awkward, launched my game to get a log file and it seems to be working now. there was a bepinex updated in-between the time of me initially testing it, not sure if that would have changed anything but my problem does seem to be solved. appreciate you taking the time to assist me!

**Comment by ToastedOven** [comment]
it honestly might have solved it. Stuff is usually out of wack during a game update, and this one was pretty damaging for some mods, even bepinex had to be updated to support it. Someone else in the discord had the issue so I'm gonna leave this open until they confirm it works for them as well

**Comment by ToastedOven** [comment]
closing this as I believe the issue to be resolved since no more reports.
