### ISSUE TITLE
currentCombatKills displaying currentCombatDamage instead

### ISSUE THREAD

**Issue by sabiacampanulata** [Wet-Boys/LookingGlass#108]
As the title says, the currentCombatKills string seems to display currentCombatDamage instead, but not the other way around.

Screenshots:
![Risk_of_Rain_2_mAh5HA3zp1](https://github.com/user-attachments/assets/48bd0272-1676-437b-8153-40041916c8dd)
Difficulty: [difficultyCoefficient]
Kills: [killCount]
Combo: [currentCombatKills] | [remainingComboDuration]

![Risk_of_Rain_2_0zl09GAYup](https://github.com/user-attachments/assets/4ae72534-9af9-4ea2-b79e-5ec322b8eea1)
Difficulty: [difficultyCoefficient]
Kills: [killCount]
Combo: [currentCombatDamage] | [remainingComboDuration]

**Comment by ToastedOven** [comment]
fixed in 1.9.2
