### ISSUE TITLE
Stats Display Issue

### ISSUE THREAD

**Issue by Brennan-King** [Wet-Boys/LookingGlass#11]
The stats display UI overlaps with the void fields UI making it hard to read.

![Screenshot 2024-05-11 181455](https://github.com/Wet-Boys/LookingGlass/assets/39571400/b96b3e7f-e7dc-4264-ae59-d2e1d4bc6ad6)

**Comment by ToastedOven** [comment]
Pushing out v1.2.3 which fixes this, thanks!
