### ISSUE TITLE
Input Disables Command Prompt does not seem to work

### ISSUE THREAD

**Issue by FinalCatalyst** [Wet-Boys/LookingGlass#111]
No controller plugged in - this setting does not seem to work. No matter what button I press the command prompt stays open. I have tried turning the setting itself on/off, tried relaunching the game with the setting on/off, and I can't seem to get it to work. Profile code is 0191c889-277c-bc2d-3433-bc7dfad47479

**Comment by ToastedOven** [comment]
fixed in 1.9.4
