### ISSUE TITLE
Default sorting order for the list of items picked up

### ISSUE THREAD

**Issue by ii3eas7** [Wet-Boys/LookingGlass#113]
When the list of items picked up are sorted by tier and stack size, items with the same rarity and stack size default to a random order. As a user it would be great if the mod could default to sorting by pickup order (least recent -> most recent) within each level of the sorting hierarchy. 

This can be tested by using console commands and granting the player the following items (in order): 
1. give_item TriTipDagger
2. give_item EnergyDrink
3. give_item AntlerShield

As a user I would expect items to show up in the following order: 
1. Tri-Tip Dagger
2. Energy Drink
3. Antler Shield

Sorting by tier and stack size, items are displayed in the following order: 
1. Tri-Tip Dagger
2. Antler Shield
3. Energy Drink

I have not tested with tier and/or stack size ordering turned off, it's currently unknown if ordering is different with these options turned off.

**Comment by ToastedOven** [comment]
I believe this got added with v1.9.7 by default with tier sort, feel free to re-open if it's still not what you expect
