### ISSUE TITLE
MUL-T's Scrap Launcher seemingly listed as 1.5 proc coefficient instead of 1.0

### ISSUE THREAD

**Issue by Pupo743** [Wet-Boys/LookingGlass#115]
![imagen](https://github.com/user-attachments/assets/e6eefdf9-f7f2-4a8a-b71f-230204c74167)

Tested via debugToolkit by giving myself 7 tritips and still some of the missiles didnt proc bleed despite the tooltip, so it is an error  and not a surprise hidden SOTS mul-t buff

**Comment by ToastedOven** [comment]
Thanks for the catch, this is probably just a typo cause the cool down is 1.5 seconds. I'll get it fixed tonight.

**Comment by ToastedOven** [comment]
fixed in 1.9.5
