### ISSUE TITLE
Scoreboard does not show player money

### ISSUE THREAD

**Issue by WesCook** [Wet-Boys/LookingGlass#122]
Looking Glass prevents player's money from showing up in the scoreboard.  In vanilla, you're able to see how much others have.  In Looking Glass, the item summaries seem to replace that value.  It would be nice to be able to show both, or to offer more control here.

Vanilla:
![Vanilla](https://github.com/user-attachments/assets/920c7ca1-ad84-40a8-8072-6caf36786063)

Looking Glass:
![Looking Glass](https://github.com/user-attachments/assets/9fd568a1-4716-4b3f-a89e-64bf8b982011)

**Comment by ToastedOven** [comment]
Fixed in v1.9.8
