### ISSUE TITLE
explodes with hunk hud

### ISSUE THREAD

**Issue by goldenguy00** [Wet-Boys/LookingGlass#129]
hunk has a custom minimal hud option that used to work just fine until the latest update

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LookingGlass.ItemCounters.ItemCounter.UpdateMoneyText (System.Action`1[T] orig, RoR2.UI.ScoreboardStrip self) (at /home/runner/work/LookingGlass/LookingGlass/LookingGlass/ItemCounters/ItemCounter.cs:70)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.UI.ScoreboardStrip::UpdateMoneyText>?-619120540(RoR2.UI.ScoreboardStrip)
RoR2.UI.ScoreboardStrip.Update () (at <a149dbd7438a4e73b97d6600b3a2bbd4>:IL_0000)
`

[LogOutput.log](https://github.com/user-attachments/files/17301147/LogOutput.log)

**Comment by goldenguy00** [comment]
oh it might be riskui actually
idk how to send the dll for you to test it, just message me on discord i guess 
![{8A2C739D-ADDC-4B91-9365-FF72EA506CD0}](https://github.com/user-attachments/assets/52eb9ab7-8a65-4b33-8f63-5bf72d45691d)

**Comment by ToastedOven** [comment]
Oh, I bet I know what it is, RiskUI probably doesn't have the new itemCountText element that was added in the newest update. I'll set it up later tonight to fall back to  the moneyText

**Comment by ToastedOven** [comment]
:widepeepoHappy3: :thumbsup:
