### ISSUE TITLE
Critwithluck calculations still seem broken with Purity.

### ISSUE THREAD

**Issue by Shiranui-Izayoi** [Wet-Boys/LookingGlass#14]
While it no longer shows 1% when having purity they still seem broken as when I picked one up my displayed crit chance increased to 121% despite having only 11% crit at the time. Thanks to having 1 irradiant pearl see image below.
![image](https://github.com/Wet-Boys/LookingGlass/assets/28239134/c9d11149-9ae2-425e-ad9b-861eb4ae650b)

**Comment by Shiranui-Izayoi** [comment]
Judging by the number the value is accidentally being multiplied by 100. Since the correct value is 1.21

**Comment by ToastedOven** [comment]
You are right, I wasn't reducing the input value (ror2 stores it as a literal value, so 100% == 100, whereas I need it as a number between 0-1 so 50% == .5)

This has been fixed in 1.2.6
