### ISSUE TITLE
New update breaks the mod

### ISSUE THREAD

**Issue by Manranzig** [Wet-Boys/LookingGlass#141]
Picking up an item doesn't show description and doesn't appear in inventory, also gives thousand of stacks

**Comment by onthecake** [comment]
i got scared when suddenly with mul-t i got supersonic speed after trying to get 1 red wip

**Comment by TheOneTrueLuke** [comment]
Can confirm, noticed the same issue while using artifact of command.

**Comment by ToastedOven** [comment]
I'll get on this later tonight or tomorrow morning

**Comment by DrewScatterday** [comment]
also noticed not working from update, thanks for your hard work! @ToastedOven

**Comment by ToastedOven** [comment]
fixed in v1.10.0

**Comment by TheOneTrueLuke** [comment]
Thanks for the work you do! @ToastedOven
