### ISSUE TITLE
Void Potential is wonky and small

### ISSUE THREAD

**Issue by Phreelosu** [Wet-Boys/LookingGlass#16]
![image](https://github.com/Wet-Boys/LookingGlass/assets/97800476/b8630513-d3a8-4d3c-a98b-9a86cb85b578)

it seems like the changes made to command artifact arent really applied to void potentials
maybe a bug? or just not implemented yet

**Comment by ToastedOven** [comment]
you are wonky and small

**Comment by AGhostBat** [comment]
collapsing potential 
![44720b646d677907c97a55d351fa572c](https://github.com/Wet-Boys/LookingGlass/assets/124941258/b2d231e0-c71f-41a5-a512-9fc35de93bf7)
![44720b646d677907c97a55d351fa572c - Copy](https://github.com/Wet-Boys/LookingGlass/assets/124941258/aa93d056-75eb-46c4-a2fc-2c2277278af7)

**Comment by ToastedOven** [comment]
wonkyn't
