### ISSUE TITLE
Scrapper Menu Items Not Staying Within The Box

### ISSUE THREAD

**Issue by RainSSR** [Wet-Boys/LookingGlass#17]
Can't currently grab a screenshot right now, but sometimes, opening up the Scrapper menu causes the items to line up in a horizontal row, rather then staying within the menu box.

Oh, also, if possible, having the Scrap menu sort the items the same way they do in the Inventory would be a nice addition.

**Comment by ToastedOven** [comment]
Added some sorting options to the command/scrap menu in 1.5.0 (fixed the bug a bit ago)
