### ISSUE TITLE
Can't Disable Item Counters

### ISSUE THREAD

**Issue by Expakun** [Wet-Boys/LookingGlass#22]
I have disabled Item Counters in Risk of Options and the Config File, but they still show up.
This happens with and without CleanerHUD.

![632360_20240518193548_1](https://github.com/Wet-Boys/LookingGlass/assets/45179004/e2e45a69-1f86-4183-b5fc-d00979fbfe83)

**Comment by ToastedOven** [comment]
yeah that would uhh.... that would happen when I literally forgot to utilize my config option... oops. I'll get this fixed for the next update
