### ISSUE TITLE
Buff Timer not showing up

### ISSUE THREAD

**Issue by Expakun** [Wet-Boys/LookingGlass#23]
I have enabled Buff Timers, but it just does not work.

![632360_20240519100940_1](https://github.com/Wet-Boys/LookingGlass/assets/45179004/7f96f1cd-5e99-4743-a1cb-8f89480d094f)

**Comment by ToastedOven** [comment]
hmm, seems fine on my end. It's probably a mod conflict, can you send me a profile code so I can check exactly what you see?

**Comment by Expakun** [comment]
018f925c-37e5-9105-2f1c-2d3a3f08ab07

**Comment by ToastedOven** [comment]
Fix on my end, will be in the next patch, thanks for the report!
