### ISSUE TITLE
The House/Myst Players break the mod entirely. 

### ISSUE THREAD

**Issue by Pineappleguy03** [Wet-Boys/LookingGlass#29]
If you have either of these mods then the UI just does not show up at all. Very strange.

**Comment by ToastedOven** [comment]
Not getting the error when testing with The House at least, do you have a r2modman profile code I could test with? Might be something more complicated
![Risk_of_Rain_2_nYTAsS8F32](https://github.com/Wet-Boys/LookingGlass/assets/49164897/96179f71-f082-4ef8-8ebd-7068d6095b76)

**Comment by Pineappleguy03** [comment]
018f93ce-547b-39df-1964-8ffc9904018a

For me it doesn't show up. But for my friend it does? It's so weird... 

![image](https://github.com/Wet-Boys/LookingGlass/assets/83521066/ff9d3e7f-cadc-4fa2-9dfe-b896c6d4b379)

**Comment by Pineappleguy03** [comment]
Adding onto this. Removing the Library mod and both characters fixes the issue.

**Comment by ToastedOven** [comment]
hmmm, if you wouldn't mind, send me a log file from when it breaks for you 
![Risk_of_Rain_2_bTpEIz8HLl](https://github.com/Wet-Boys/LookingGlass/assets/49164897/9458386d-6715-41d9-a816-4ae2e24a00b1)
I'm seeing it on both client and host

**Comment by Pineappleguy03** [comment]
I... Think It Fixed Itself.

![image](https://github.com/Wet-Boys/LookingGlass/assets/83521066/6bce8bf0-cf8b-40fd-b208-25dd54f7facf)

**Comment by Pineappleguy03** [comment]
That was odd.

**Comment by ToastedOven** [comment]
uhhhh, I'll leave this issue open, if you don't notice an error in the next like week, I'm gonna call it a mystery and close this out

**Comment by Pineappleguy03** [comment]
I will say though. Thanks a lot for the fast responses! I was worried that it would be a week or something.

**Comment by Pineappleguy03** [comment]
HEY! Back again! The mod got disabled again. BUT. I have the logs this time!
[LogOutput.log](https://github.com/Wet-Boys/LookingGlass/files/15378506/LogOutput.log)

**Comment by Pineappleguy03** [comment]
Well... Not disabled. But it just doesn't show stats

**Comment by Pineappleguy03** [comment]
![image](https://github.com/Wet-Boys/LookingGlass/assets/83521066/bff541fc-24ba-4b3b-8c8b-1b434d3a3cb1)

**Comment by ToastedOven** [comment]
oooh awesome (well I guess not awesome) I'll get on it

**Comment by Pineappleguy03** [comment]
I would say awesome. Now the issue can be fixed!!!

**Comment by ToastedOven** [comment]
out of curiosity (I'm not familiar with The House) did you transform into a different mob?

**Comment by Pineappleguy03** [comment]
I did turn into a scavenger... During my run. But yes.

**Comment by ToastedOven** [comment]
well, I found the issue
![notepad++_q9K8Q1hCM9](https://github.com/Wet-Boys/LookingGlass/assets/49164897/e2e1baa0-4b02-48f1-b6e6-f4aada15d06e)
it (at least for a very brief moment) transformed you to 
![Risk_of_Rain_2_tRy2VD907S](https://github.com/Wet-Boys/LookingGlass/assets/49164897/cc329669-b3b0-47e0-8537-53e2aa5c76bc)
which even though it visually doesn't break yet, it actually is and won't return as a result.

This is an oversight on my behalf where a few of the stats check for stats that some mobs do not have, while not having a failsafe for them not existing. Solution is pretty straightforward thankfully

**Comment by ToastedOven** [comment]
![bepinex_gui_ICDht6bDDq](https://github.com/Wet-Boys/LookingGlass/assets/49164897/8b4128a3-83ea-4c0e-8a08-499894602e6c)

**Comment by Pineappleguy03** [comment]
Phew... Glad it's not a huge error!

**Comment by ToastedOven** [comment]
Should be fixed in 1.4.2, but feel free to re-open this if you still see issues
