### ISSUE TITLE
[suggestion] order stuff

### ISSUE THREAD

**Issue by surytrap** [Wet-Boys/LookingGlass#3]
add an option to sort by order found (like vanilla)

reverse too

maybe make the vanilla order compatible wiht putting scrap separately too

because currently if you disable everything except scrap tickbox the items are ordered seemingly randomly, including the scrap

**Comment by Rune580** [comment]
the order found behavior can be enabled simply by disabling everything except the Separate Scrap option, as for reversing the order found, we'll look into it

**Comment by ToastedOven** [comment]
Fixed this in v1.2.1 you should be able to have just scrap sorted properly now
