### ISSUE TITLE
Stats display float precision 

### ISSUE THREAD

**Issue by aembur** [Wet-Boys/LookingGlass#30]
Due to precision errors, all float values in the stats display should have a limit to their decimal places. A lot of them already seem to have a 3 decimal place limit, but regen doesn't, and this happens quite often:

![image](https://github.com/Wet-Boys/LookingGlass/assets/55598133/79ccac0b-eec0-4ed9-96d9-06f32d7c206a)

Not sure what other stats would need fixing, regen is the only one I've noticed so far.

**Comment by Nordblum** [comment]
Same with Base Damage. A parameter "how many digits after the dot" in the options or just making it like 2 digits max would be very cool.

**Comment by ToastedOven** [comment]
Added in 1.4.1, thanks for the report!
