### ISSUE TITLE
DPS stat not resetting between runs

### ISSUE THREAD

**Issue by aembur** [Wet-Boys/LookingGlass#31]
Leaving a run when DPS is not 0 carries it over to the next run as base DPS. Steps to reproduce:

1. Start a new run
2. Do some damage
3. Leave to menu before DPS stat decays to 0
4. Start a new run
5. Look at DPS stat

![image](https://github.com/Wet-Boys/LookingGlass/assets/55598133/21555032-afc8-4647-ad8d-f6679f2bb5bd)

**Comment by ToastedOven** [comment]
fixed in 1.4.2, thanks for the report!
