### ISSUE TITLE
1.4.0 update breaks compatibility with RiskUI

### ISSUE THREAD

**Issue by Ichofox** [Wet-Boys/LookingGlass#32]
In version 1.3.2, with RiskUI:
![20240520202040_1](https://github.com/Wet-Boys/LookingGlass/assets/98953318/c3ee955c-0c9e-48dc-a3f0-3f051c25fce8)

And in version 1.4.0, with RiskUI:
![20240520201829_1](https://github.com/Wet-Boys/LookingGlass/assets/98953318/0b1ddfb2-4618-4ebb-bdd1-ff593203656f)

Not sure _what_ broke it in the update, but can consistently cause/fix the issue by switching versions.

**Comment by ToastedOven** [comment]
1.4.1 fixes this, sorry about that
