### ISSUE TITLE
Item Descriptions broken.

### ISSUE THREAD

**Issue by Ryu776** [Wet-Boys/LookingGlass#35]
have no idea if its another mod, but items from popular mods such as starstorm, LiT, MysticsItems, Aetherium, and so on aren't working. no item descriptions in command window. if its a known issue from another mod, it would be greatly appreciated to know which is the culprit. if its just not compatible with those mods I HIGHLY recommend fixing it since literally EVERYONE uses them and your mod would be useless.

**Comment by ToastedOven** [comment]
Works with a minimal setup 
![Risk_of_Rain_2_YMjQNi0RxE](https://github.com/Wet-Boys/LookingGlass/assets/49164897/a37910e2-dd9d-46a9-98d9-b84392a96522)
could you send me a profile code from your side so I can test. I am not aware of any current incompats

**Comment by Ryu776** [comment]
did some testing myself by reinstalling starstorm which seemed to fix it. seems to be a load order issue maybe?

**Comment by ToastedOven** [comment]
Depending on when you had issues today, it might have been due to the update. 
![r2modman_UavFNcpeY0](https://github.com/Wet-Boys/LookingGlass/assets/49164897/496af813-6103-421f-8a31-b1a7b248546f)
got updated an hour ago or so and fixed like 90% of issues people were having

**Comment by ToastedOven** [comment]
gonna close this out, but feel free to re-open if you notice the issue again
