### ISSUE TITLE
Can't scrolling in command options

### ISSUE THREAD

**Issue by ViruzSS** [Wet-Boys/LookingGlass#4]
Can't scrolling down in command options. When I try it comes back immediately.
![image](https://github.com/Wet-Boys/LookingGlass/assets/168935089/a18786b1-dbd1-476b-8229-59a281697ee0)

**Comment by ToastedOven** [comment]
Our mod doesn't have scrolling in the command menu (it resizes instead), can you send me a profile code so I could see exactly what's going on?

**Comment by ViruzSS** [comment]
Where it exactly?

**Comment by ToastedOven** [comment]
![r2modman_gwrAjssXSu](https://github.com/Wet-Boys/LookingGlass/assets/49164897/1ceba3de-4d88-4af2-b236-8b621f7109c5)

**Comment by ViruzSS** [comment]
018f4562-f491-3435-19f0-141ab4dc29c9

**Comment by ToastedOven** [comment]
![Risk_of_Rain_2_zXeFDxjOUV](https://github.com/Wet-Boys/LookingGlass/assets/49164897/27d272dc-835f-475a-9afb-c57fd17208d9)
happens even with LookingGlass disabled
![r2modman_H9987i6JOR](https://github.com/Wet-Boys/LookingGlass/assets/49164897/911a24fb-7c41-4f9d-94ba-f88f27653a13)

**Comment by ToastedOven** [comment]
I would contact Dragonyck on the modding discord about this, since it's only happening with his mod turned on https://discord.gg/5MbXZvd

**Comment by ViruzSS** [comment]
Ok
