### ISSUE TITLE
Conroller Players completely unable to select items already owned via command artifact

### ISSUE THREAD

**Issue by FlowerCow** [Wet-Boys/LookingGlass#43]
When playing with the artifact of command on controller with this mod, everything can be selected in the essence window just fine the first time around.  But once you collect a single item, that item gets moved to the front and can no longer be navigated to.  I have to switch to kbm to select items, and it's a chore to swap between modes so frequently.

**Comment by Oroborius** [comment]
Still not fixed.

**Comment by ToastedOven** [comment]
can you send a profile code? last I checked it was working fine, maybe something came up
