### ISSUE TITLE
suggestion: add a tracker for portals in the current stage

### ISSUE THREAD

**Issue by LunarrEclipse** [Wet-Boys/LookingGlass#44]
a tracker for the types of portals and if they ahd been activated would be nice to add to the ui, preferably hidden unless tabbed.

**Comment by ToastedOven** [comment]
That is already present, the default config for the secondary statsDisplay already utilizes it. Check your config, you probably need to enable it as I left it off by default
![Risk_of_Rain_2_ZdeDT0uNWM](https://github.com/Wet-Boys/LookingGlass/assets/49164897/d9895888-887d-4641-b5b4-62cfec804b2b)

![devenv_P864EUxIBr](https://github.com/Wet-Boys/LookingGlass/assets/49164897/f9fdd4f1-a4fc-47b0-8801-4606b825563a)
`Gold:[goldPortal] Shop:[shopPortal] Celestial:[msPortal] Void:[voidPortal]`

**Comment by LunarrEclipse** [comment]
ah apologies, thanks for the info!
