### ISSUE TITLE
Suggestion for Stats display

### ISSUE THREAD

**Issue by AceKuper** [Wet-Boys/LookingGlass#45]
Is there a way to add Current multikill and Highest mutlikill to Stats Display? I thought maxCombo would do one of them, but i'm not sure what number it gives, since mine is unchanging 4 digit 1055.

**Comment by ToastedOven** [comment]
combo/maxCombo is damage dealt kinda thing. I'll see about adding multikill stuff in the next update

**Comment by ToastedOven** [comment]
added in 1.6.0:
maxComboThisRun, currentCombatKills, maxKillCombo, maxKillComboThisRun
