### ISSUE TITLE
[Incompatibility] LookingGlass crashes when Aetherium is enabled

### ISSUE THREAD

**Issue by Imper1um** [Wet-Boys/LookingGlass#48]
**Related Mod:** https://github.com/KomradeSpectre/AetheriumMod
**Aetherium Version:** v0.6.8
**LookingGlass Version:** v1.6.1

When both Aetherium and LookingGlass is enabled, the game crashes prior to starting a log. No logs are available through the BepinEx Log Manager.

This was confirmed by disabling Aetherium with LookingGlass Enabled (and the game launches just fine), and then enabling Aetherium while disabling Looking Glass. When both Aetherium and LookingGlass is enabled at the same time, the game does not even launch, nor does BepinEx start a log at all.

**Comment by Imper1um** [comment]
Ticket 72 was created in Aetherium's GitHub to connect the two: https://github.com/KomradeSpectre/AetheriumMod/issues/72

**Comment by Imper1um** [comment]
018fbfef-a640-4449-11d7-7f3a28385bd0

I'll try it without the other addons.

**Comment by Imper1um** [comment]
Nope, even if I disable all the mods and then *only* enable LookingGlass *and* Aetherium (which enables the dependencies), it crashes on Boot.

**Comment by Imper1um** [comment]
So:
 - Enable everything *but* Aetherium: Works
 - Enable everything *but* LookingGlass: Works
 - Enable nothing except Aetherium and it's Dependencies: Works
 - Enable nothing except LookingGlass and it's Dependencies: Works
 - Enable nothing except LookingGlass, Aetherium and their two Dependencies: Crashes on Boot
 - Enable everything: Crashes on Boot

**Comment by ToastedOven** [comment]
if you just launch the game on it's own, what do you see in the top left? I see 
![Risk_of_Rain_2_5E9rco4euP](https://github.com/Wet-Boys/LookingGlass/assets/49164897/bdf1b9f2-e4bc-4b4c-babf-5711ce5de738)

**Comment by Imper1um** [comment]
Same
![image](https://github.com/Wet-Boys/LookingGlass/assets/49252077/cef137eb-9b53-4658-9da5-8543f8ea6ac7)

**Comment by ToastedOven** [comment]
Hmm, can you try sending me a Player.log from a failed launch? These get created even with a crash, might point to something

%appdata%/../LocalLow/Hopoo Games, LLC/Risk of Rain 2
![explorer_1ioAN71c4D](https://github.com/Wet-Boys/LookingGlass/assets/49164897/ad12e3ce-bdfd-4eae-b707-d6cac7cdee36)

**Comment by ToastedOven** [comment]
well that points to one potential problem. Can you verify your game files? 
![steamwebhelper_5p98mfegtR](https://github.com/Wet-Boys/LookingGlass/assets/49164897/6f8be2bb-a6cc-49d8-afdd-7b7c47b91a87)
I know it sounds unrelated, but the most recent ror2 update kinda messed with some things and a bunch of related issues came up during the first day or so of the update being out

**Comment by Imper1um** [comment]
Sorry it took a bit (I had to do some work), I did one up on that: I reinstall RoR2 completely, and cleared the Thunderstore Cache.

This did not change anything: the game will only launch if either Aetherium or LookingGlass (or both) are disabled.

It looks like there is a log that is finally produced now:

[Message:   BepInEx] BepInEx 5.4.21.0 - Risk of Rain 2 (5/28/2024 6:35:43 PM)
[Info   :   BepInEx] Running under Unity v2019.4.37.106033
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] Loaded 1 patcher method from [FixPluginTypesSerialization 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.GUI.Loader 1.0.0.0]
[Error  :   BepInEx] Failed to load patcher [FixPluginTypesSerialization.FixPluginTypesSerializationPatcher]: An item with the same key has already been added. Key: [FixPluginTypesSerialization/FixPluginTypesSerialization.FixPluginTypesSerializationPatcher, BepInEx.Preloader.Patching.PatcherPlugin]
[Debug  :   BepInEx] System.ArgumentException: An item with the same key has already been added. Key: [FixPluginTypesSerialization/FixPluginTypesSerialization.FixPluginTypesSerializationPatcher, BepInEx.Preloader.Patching.PatcherPlugin]
  at System.Collections.Generic.TreeSet`1[T].AddIfNotPresent (T item) [0x0001a] in <6b80e2850f1c48e6a227f0818ca6b227>:0 
  at System.Collections.Generic.SortedSet`1[T].Add (T item) [0x00000] in <6b80e2850f1c48e6a227f0818ca6b227>:0 
  at System.Collections.Generic.SortedDictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00020] in <6b80e2850f1c48e6a227f0818ca6b227>:0 
  at BepInEx.Preloader.Patching.AssemblyPatcher.AddPatchersFromDirectory (System.String directory) [0x00182] in <2a6f9c6c36c248ffbc7c6bf7c7557647>:0 
[Info   :   BepInEx] Loaded 1 patcher method from [FixPluginTypesSerialization 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.2.1.0]
[Info   :   BepInEx] 4 patcher plugins loaded
[Info   :BepInEx.GUI.Loader] Finding and launching GUI
[Info   :BepInEx.GUI.Loader] Found bepinex_gui v3 executable in C:\Users\zsylv\AppData\Roaming\Thunderstore Mod Manager\DataFolder\RiskOfRain2\profiles\Fun Times\BepInEx\patchers\RiskofThunder-BepInEx_GUI\BepInEx.GUI\bepinex_gui.exe
[Info   :BepInEx.GUI.Loader] [SendLogToClient] Accepting Socket.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Message:FixPluginTypesSerialization] Using the config cache
[Info   :FixPluginTypesSerialization] Running under Unity v2019.4.37
[Debug  :FixPluginTypesSerialization] Unity version obtained from main application module.
[Info   :   BepInEx] Patching [RoR2] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished


Looking at this log it might be FixPluginTypesSerialization, but I'll see if anything is reported on that side.

**Comment by Imper1um** [comment]
Nope, this is a generic thing used across multiple titles, and has no tickets open for this issue.

**Comment by ToastedOven** [comment]
wait a minute, that actually is useful! FixPluginTypeSerialization got a very important update the day of the update to prevent mods from conflicting seemingly at random. 
![firefox_UkvO9M0U6P](https://github.com/Wet-Boys/LookingGlass/assets/49164897/436e8eed-fbe0-4335-837f-a23444fc1507)
 And in your log you sent just now, it's basically saying it tried to load it twice, meaning it's ignoring the second time and just going with the first. I'm thinking you have a stale DLL in there that is loading first. Have you tried making a fresh profile yet? That might let it clean out the old DLL

**Comment by Imper1um** [comment]
Yup, that was the issue. It looks like the old Aetherium is trying to latch on to another FPTS DLL, but the BepInEx has a backup system when it can't do that. However, when you load Aetherium, its fine, because it only needs one DLL. However, with both DLLs there and you attempt to load both Aetherium and LG, its now attempting to load two FPTS DLLs, and the system fails when it is initializing the DLLs.

Nice catch.

**Comment by ToastedOven** [comment]
gonna close this out, glad we could get it worked out, I'm probably gonna bookmark this for the future if anyone else has dupe mods installed lol
