### ISSUE TITLE
Command menu not resizing properly

### ISSUE THREAD

**Issue by UnsavedTrash** [Wet-Boys/LookingGlass#49]
This submission is on behalf of @snowzkitty on discord

modpack code: 018fb2f2-f326-64a2-5fa1-6ae43a975550

[Log File](https://github.com/Wet-Boys/LookingGlass/files/15445976/message.txt)

![image](https://github.com/Wet-Boys/LookingGlass/assets/75506304/ff77b24d-c44e-4f00-8360-8fc78590b044)

**Comment by ToastedOven** [comment]
Updating my mods fixed the issue, this is correlated by the update logs from TMI 
![firefox_9PQCXlKfp1](https://github.com/Wet-Boys/LookingGlass/assets/49164897/4e04954f-9fa9-478b-a7fb-9fab039729d1)
