### ISSUE TITLE
Cooldown not shown correctly on other players use items

### ISSUE THREAD

**Issue by UnsavedTrash** [Wet-Boys/LookingGlass#50]
Submitted on behalf of @firebuggy on discord

"lookingglass shows the cooldown properly except when checking other players' items in multiplayer"

![image](https://github.com/Wet-Boys/LookingGlass/assets/75506304/1c1bbb81-6479-49bf-a562-fd98fe4ba332)

**Comment by shirograhm** [comment]
I made a fix for this, see https://github.com/Wet-Boys/LookingGlass/pull/54

**Comment by ToastedOven** [comment]
thanks for the fix, pushed out in 1.6.2
