### ISSUE TITLE
Allow changing the order that tiers are sorted

### ISSUE THREAD

**Issue by UnsavedTrash** [Wet-Boys/LookingGlass#51]
"the main thing i hate coming from BetterUI is the sort order of your items. I need yellow, red, green, white. Yellow being at the end just bothers me"

https://old.reddit.com/r/RiskofRain2_Mods/comments/1cxhzzy/improvedui_by_dragonyck_wont_work/l5n6tro/

**Comment by ToastedOven** [comment]
SSM240 has addressed this in v1.8.0
