### ISSUE TITLE
Game doesn´t launch with LookingGlass enabled

### ISSUE THREAD

**Issue by truefrui** [Wet-Boys/LookingGlass#56]
Just as the title says.  Other mods i use: ProperSave, EmptyChestsBeGone, SkipIntro, RTAutoSprintEx, ActuallyFaster, PrintToInventory, RiskUI. I wanted to use this mod since BetterUI doesn´t work anymore, but sadly LookingGlass doesn´t work aswell xD.

Thanks for your help in advance, let me know if you need more info.

**Comment by truefrui** [comment]
No idea how but i guess after installing ItemStats aswell it started to work lmao

**Comment by ToastedOven** [comment]
Hey, do you have a profile code I could use to get the full mod list so I can test on my end why this happened? Or is the list you have 100% complete?

**Comment by truefrui** [comment]
Yes sure! Here: 018fd0af-5976-ae01-09e1-afe5731b9a6b. But as i said above after also installing ItemStats it started to work, before that w/o ItemStats it didnt though i dont know why

**Comment by ToastedOven** [comment]
hmmm, using that code and disabling ItemStats, it launches fine for me. Not sure where to go with this if you got it working on your end. I might just close it out unless you feel like doing further debugging

**Comment by truefrui** [comment]
I just tried again without ItemStats and it didnt work again, but since its working for me now with it enabled, we can close this one out. Thanks for your fast response though!
