### ISSUE TITLE
Game not launching (code included)

### ISSUE THREAD

**Issue by sb8244** [Wet-Boys/LookingGlass#57]
I ran into a crash on my wife's computer. We both use the profile `018fd1c2-61f6-d62b-f4c8-1cbd6da03dac`. Her game starts with the mod disabled, but crashes (no visible messages or modals) with the mod enabled. 

Everything works great for me. My profile has everything enabled and is same export code as hers.

**Comment by ToastedOven** [comment]
so I've seen this issue on a few people's ends. By chance did her profile exist before the most recent game update? She might need to create a new profile based off of the export code. Some mods ended up duped and caused crashes in weirdly specific scenarios. See https://github.com/Wet-Boys/LookingGlass/issues/48#issuecomment-2136261659 where a very similar scenario happened

**Comment by sb8244** [comment]
Thanks for that! That seems to fix it
