### ISSUE TITLE
"healthPercentage" Stat is not affected by "StatsDisplay Float Precision."

### ISSUE THREAD

**Issue by GeodeFortyFive** [Wet-Boys/LookingGlass#58]
Simple enough on the tin; even if it's not bug, it is quite jarring when seeing the stat having a longer decimal point then the other stats that have less then the Float Precision value set.
![image](https://github.com/Wet-Boys/LookingGlass/assets/111404774/c619f5ca-6479-4d73-852a-8455a018f909)

**Comment by ToastedOven** [comment]
fixed in 1.6.3
