### ISSUE TITLE
equipment doesn't show detailed description on pickup

### ISSUE THREAD

**Issue by Thorebourne** [Wet-Boys/LookingGlass#59]
i have no idea if this is an intentional feature or not, but equipment doesn't show it's detailed description when pinged or picked up, but only when hovered over in the inventory.
![20240601204158_1](https://github.com/Wet-Boys/LookingGlass/assets/102445121/6d30e7aa-772b-43ae-8f2c-4c038df7a1e6)
![20240601204214_1](https://github.com/Wet-Boys/LookingGlass/assets/102445121/3abde12c-423f-4c74-ab44-fc5c4bad2ede)
![20240601204350_1](https://github.com/Wet-Boys/LookingGlass/assets/102445121/45c1e3f2-b4d3-44ef-92cc-02fb1de54aa5)

**Comment by ToastedOven** [comment]
It was not intentional. I fixed it in 1.7.0, thanks for the report
