### ISSUE TITLE
[Request] Show environment name on inventory (tab) screen.

### ISSUE THREAD

**Issue by maverick-hunter** [Wet-Boys/LookingGlass#69]
Sorry if this doesn't belong in the scope of this mod, but I though it wouldn't hurt to ask!

Here's the thing: I don't really know if it's the intended behavior or if its a Risk UI bug, but it doesn't show the environment (map) name at the beginning of a stage. Since Looking Glass seems make more changes to the inventory screen than Risk UI, that could be a nice option, maybe?

It's kind of an interesting bit of info to have, especially when paired with something like StageAesthetics, which seem to fit nicely with the kind of info presented by Looking Glass.

**Comment by ToastedOven** [comment]
Seems to be a riskui issue cause without it I see the stage name. Either way, Warmek added this in the 1.8.0 update
