### ISSUE TITLE
new addition of luck calculation bug

### ISSUE THREAD

**Issue by kostas19dimitris** [Wet-Boys/LookingGlass#72]
If i am not mistaken the moment you pick up a leaf clover after having 10 or above [Lens-Maker's Glasses] the crit chance messes up and if you have too many [Lens-Maker's Glasses] the crit chance even goes to the negatives. The effect does not change (you still hit a crit every time ) what changes is the number or the indication above .
![with leaf](https://github.com/Wet-Boys/LookingGlass/assets/137660339/9975a385-2344-465b-892b-4494514794ce)
![without leaf](https://github.com/Wet-Boys/LookingGlass/assets/137660339/949b5280-3a07-492c-96fb-037472101252)

**Comment by ToastedOven** [comment]
sorry about that, getting it fixed really quick
