### ISSUE TITLE
Unclear method signature + wrong description

### ISSUE THREAD

**Issue by yaggod** [Wet-Boys/LookingGlass#74]
Second argument of  [Utils.GetExponentialRechargeTime](https://github.com/Wet-Boys/LookingGlass/blob/1bd7cb022c2d32e6591ffdc5d137a28eedd9fdd2/LookingGlass/Utils.cs#L37) looks really unclear since it is literally just a coefficient of the base cooldown. 
![image](https://github.com/Wet-Boys/LookingGlass/assets/71946695/83605874-454b-4550-a9d6-fc710c428b59)

Since i am not sure about its meaning, i dont know what exactly it is supposed to be in [safer spaces](https://github.com/Wet-Boys/LookingGlass/blob/1bd7cb022c2d32e6591ffdc5d137a28eedd9fdd2/LookingGlass/ItemStats/ItemDefinitions.cs#L1971) description, but in its present form it is causing wrong safer spaces description, which correct formula have to be 15x0.9^(n-1), but instead it is 1.5x0.9^(n-1) 
![image](https://github.com/Wet-Boys/LookingGlass/assets/71946695/5ceb65eb-4dea-41e5-85b7-c87f82a6d94f)

**Comment by ToastedOven** [comment]
fixed in 1.7.3
