### ISSUE TITLE
Safer Spaces Item Description Value Wrong

### ISSUE THREAD

**Issue by Cbrad24** [Wet-Boys/LookingGlass#75]
The item description computed value for some items is wrong. I don't think this became an issue until I updated to v1.7.1, currently running v1.7.2.

Not sure this is limited to just Safer Spaces but I can provide more testing and evidence later today, just wanted to get the ball rolling.

Easy to replicate, just have one or two Safer Spaces, and observe the computed time on item hover is only like 1 or 2 seconds, when it should be a much higher cooldown of 12-13 seconds.

**Comment by Cbrad24** [comment]
Just noticed this is a possible duplicate of #74.

**Comment by ToastedOven** [comment]
fixed in 1.7.3
