### ISSUE TITLE
game closes immediately with the mod installed

### ISSUE THREAD

**Issue by aridiamond** [Wet-Boys/LookingGlass#76]
recently i couldn't open the game with mods. it closes after a few seconds, stopping the log after the preloader finishes
[LogOutput.log](https://github.com/user-attachments/files/15995758/LogOutput.log)
it sometimes flashes an error popup
mod is installed through thunderstore and i have the game on steam

**Comment by ToastedOven** [comment]
I've seen this happen in various scenarios after the most recent update to ror2. Usually just exporting your profile code and creating a new one off that fixes the issue

**Comment by ToastedOven** [comment]
I'm going to assume this was fixed since I haven't heard anything else on it. Feel free to re-open if the above fix didn't work
