### ISSUE TITLE
Stats that show percentage factoring in luck.

### ISSUE THREAD

**Issue by Shiranui-Izayoi** [Wet-Boys/LookingGlass#8]
Assuming it isn't annoying to implement could we get stats that factor in luck? So for example crit chance when factoring in luck or item proc chances when factoring in luck?

I would guess these would be seperate from the normal stats and might be a toggle in the config/options or just a seperate stat that you can put the syntax for.

I am pretty sure they don't factor it in yet.

**Comment by ToastedOven** [comment]
Added this in 1.2.1 with critWithLuck and bleedChanceWithLuck. the critWithLuck is the new default for crit. But that's just default config options, so you might need to change your setup to accommodate it
