### ISSUE TITLE
How to continue to top item scrap in the new version 1.8.0?

### ISSUE THREAD

**Issue by Lishang0321** [Wet-Boys/LookingGlass#87]
droppod.lookingglass.cfg

"Seperate Scrap = true"

i found this one , but it seems useless

**Comment by ToastedOven** [comment]
I don't recommend using direct config files. You can adjust stuff in game and see real-time changes.

You can change where scrap gets put here
![Risk_of_Rain_2_i5oq0YHVUd](https://github.com/Wet-Boys/LookingGlass/assets/49164897/e4be79fd-8917-47ad-93cf-1d38c433927b)
