### ISSUE TITLE
dosnt hide locked iteams

### ISSUE THREAD

**Issue by lioni-a** [Wet-Boys/LookingGlass#88]
even with unhide hidden items set to false it still shows them not leting you see the unlock challenge
![image](https://github.com/Wet-Boys/LookingGlass/assets/162006280/c8697bdf-b63f-4054-93d0-bc7b0f8ac414)
![IMG_20240704_093239](https://github.com/Wet-Boys/LookingGlass/assets/162006280/28aa6f3f-b7b9-44c0-b007-e8f69503d2ff)
used a phone sense its hard to sceenshot with menu closing

**Comment by ToastedOven** [comment]
That's not what that setting does. Hidden items are like the items the game gives you automatically for playing on drizzle mode.
