### ISSUE TITLE
Scrap sorting seems bugged

### ISSUE THREAD

**Issue by Shiranui-Izayoi** [Wet-Boys/LookingGlass#9]
I saw the issue with the suggestion on sorting and saw that apparently the order found behavior can be enabled simply by disabling everything except the Separate Scrap option. So I tried it, and admittedly this might be a case of things being bugged, if you change them mid run. But it doesn't work the items are sorted randomly.

That said if all options are enabled it sorts scrap properly to the top. If not then it seems to sort them kinda wherever. Not sure why. The following image is what my inventory looks like with just sort scrap enabled.
![image](https://github.com/Wet-Boys/LookingGlass/assets/28239134/d9a9def4-051a-45ee-87b0-6f9d82aab2c5)

While this is with all options enabled. And it works fine.
![image](https://github.com/Wet-Boys/LookingGlass/assets/28239134/3dcd5911-7d89-472e-b534-491ea69621cb)

Along with that there is a second issue of a unfinished item (according to wiki) called "aacannon" showing up randomly when only sort scrap is enabled.  I think it mostly shows up after you use the last of any particular scrap. Or maybe just using scrap not 100% sure.

This ghost item doesn't exist in the inventory nor does it do anything, you just get an untextured purple error symbol. See image below.
![image](https://github.com/Wet-Boys/LookingGlass/assets/28239134/4250de07-e203-4208-bb50-af2c32bd9f2e)

**Comment by ToastedOven** [comment]
Pushed a fix for this in v1.2.1, feel free to re-open if you still have issues
