### ISSUE TITLE
[Request] Display crit chance beyond 100%

### ISSUE THREAD

**Issue by 4AC11** [Wet-Boys/LookingGlass#92]
Unsure if this is the right place for this, but ever since moving from BetterUI to LookingGlass the one thing that has consistently bothering me as being missing is the fact that Crit Chance maxxes out at 100%. I play with Hypercrit, so functionally my crit chance does not max at 100%, and with BetterUI I could see the chance for a double or triple crit easily, while with LookingGlass it's much more of a pain to figure out how much my extra crit chance is doing for me, or to know if modded items are adding crit chance beyond 100% properly.

**Comment by ToastedOven** [comment]
added in 1.8.4, thanks @SSM240!
![Risk_of_Rain_2_VvvCUjzZbj](https://github.com/user-attachments/assets/0b2beb2d-04b3-4079-916b-50c5e55be8a3)
